name: Generate Snake Animation

on:
  schedule:
    # Runs every day at midnight UTC
    - cron: "0 0 * * *"
  workflow_dispatch: # Allows manual triggering

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      # Checkout your repository
      - uses: actions/checkout@v4

      # Generate the snake SVG
      - uses: Platane/snk@v3
        with:
          github_user_name: hemantsinha01 # Replace with your GitHub username
          outputs: |
            output/github-contribution-grid-snake.svg
            output/github-contribution-grid-snake-dark.svg # Dark theme version

      # Commit and push the generated files
      - name: Commit the snake SVGs
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add output/*
          git commit -m "Update snake animation" || echo "No changes to commit"
          git push
